[project]
name = "pinot-noir"
version = "0.1.0"
description = "Django web application using UBQ, providing reports on the status of Ubuntu packages in terms of merges, bug fixes, etc. organized in a team-focused way."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=45.0.0",
    "django>=5.2,<6.0",
    "django-tasks>=0.12.0",
    "django-tasks-db>=0.12.0",
    "psycopg[binary]>=3.3.4",
    "python-debian>=1.1.0",
    "pyyaml>=6.0",
    "ubq>=0.5.1",
]

[dependency-groups]
format = [
    "ruff>=0.15.12",
]
lint = [
    "codespell>=2.4.2",
    "django>=5.2,<6.0",
    "ty>=0.0.34",
    "types-pyyaml>=6.0",
]

[tool.ruff]
line-length = 99

[tool.ruff.lint]
select = ["E", "F", "I", "PL", "W"]
