[tox]
envlist =
    lint
recreate = true

[testenv]
package = skip

[vars]
project_path = {tox_root}/pinot_noir
merges_schedule_path = {tox_root}/merges_schedule
reviews_path = {tox_root}/reviews
launchpad_path = {tox_root}/launchpad
all_path = {[vars]project_path} {[vars]merges_schedule_path} {[vars]reviews_path} {[vars]launchpad_path}

[testenv:format]
description = Apply coding style standards to code
dependency_groups = format
commands =
    isort {[vars]all_path}
    black {[vars]all_path}

[testenv:lint]
description = Check code against coding style standards
dependency_groups =
    lint
    format
commands =
    black --check --diff {[vars]all_path}
    codespell {[vars]all_path}
    isort --check-only --diff {[vars]all_path}
    mypy {[vars]src_path}
    pflake8 {[vars]all_path}
    pylint {[vars]all_path}