# Generated by Django 5.2 on 2026-05-12 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackportBugPackageInfo",
            fields=[
                (
                    "name",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("package_names_combined", models.CharField(max_length=600)),
                ("milestone_offset", models.IntegerField(default=0)),
                ("description_template", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="LPReviewMarkerUser",
            fields=[
                (
                    "username",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MergeBugPackageInfo",
            fields=[
                (
                    "package",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("milestone_offset", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lp_token", models.CharField(max_length=1000)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Tokens",
                "verbose_name_plural": "User Token Groups",
            },
        ),
    ]
