# Generated by Django 5.2 on 2026-05-14 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_manager", "0001_initial"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backportbugpackageinfo",
            name="package_names_combined",
            field=models.CharField(default="", max_length=600),
        ),
        migrations.CreateModel(
            name="MergeBugFilterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tags_combined", models.CharField(default="", max_length=600)),
                ("subscribers_combined", models.CharField(default="", max_length=600)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
        ),
    ]
