# Generated by Django 5.2 on 2026-05-15 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_manager",
            "0002_alter_backportbugpackageinfo_package_names_combined_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BackportBugFilterSettings",
            fields=[
                (
                    "mergebugfiltersettings_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="data_manager.mergebugfiltersettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backport Bug Filter Setting",
                "verbose_name_plural": "Backport Bug Filter Settings",
            },
            bases=("data_manager.mergebugfiltersettings",),
        ),
        migrations.AlterModelOptions(
            name="mergebugfiltersettings",
            options={
                "verbose_name": "Merge Bug Filter Setting",
                "verbose_name_plural": "Merge Bug Filter Settings",
            },
        ),
    ]
