# Generated by Django 5.2 on 2026-05-15 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_manager", "0004_mergebugfiltersettings_settings_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackportBugFilterSettings",
            fields=[],
            options={
                "verbose_name": "Backport Bug Filter Setting",
                "verbose_name_plural": "Backport Bug Filter Settings",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("data_manager.mergebugfiltersettings",),
        ),
    ]
