# Generated by Django 5.2 on 2026-05-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_manager", "0005_backportbugfiltersettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backportbugpackageinfo",
            options={
                "verbose_name": "Backport Bug Package Info",
                "verbose_name_plural": "Backport Bug Package Info Sets",
            },
        ),
        migrations.AlterModelOptions(
            name="mergebugpackageinfo",
            options={
                "verbose_name": "Merge Bug Package Info",
                "verbose_name_plural": "Merge Bug Package Info Sets",
            },
        ),
        migrations.AddField(
            model_name="backportbugpackageinfo",
            name="bug_filed_this_cycle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mergebugpackageinfo",
            name="bug_filed_this_cycle",
            field=models.BooleanField(default=False),
        ),
    ]
