# Generated by Django 5.2 on 2026-05-19 00:00

import pinot_noir.data_manager.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_manager", "0006_alter_backportbugpackageinfo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertokens",
            name="lp_token",
            field=pinot_noir.data_manager.fields.EncryptedTextField(),
        ),
    ]
