# Generated by Django 5.2 on 2026-06-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_manager", "0007_alter_usertokens_lp_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mergebugfiltersettings",
            name="subscribers_combined",
            field=models.CharField(blank=True, default="", max_length=600),
        ),
    ]
