# Generated by Django 5.2

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_manager", "0008_alter_mergebugfiltersettings_subscribers_combined"),
        ("launchpad", "0005_lpuser_is_team_member_lpuser_is_review_marker"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LPReviewMarkerUser",
        ),
    ]
