# Generated by Django 5.2 on 2026-07-16 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_manager", "0009_delete_lpreviewmarkeruser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        choices=[
                            ("refresh_reviews", "Refresh reviews"),
                            ("prune_task_results", "Prune task results"),
                            ("refresh_merge_schedule", "Refresh merge schedule"),
                            ("submit_merge_bugs", "Submit merge bugs"),
                            ("submit_backport_bugs", "Submit backport bugs"),
                        ],
                        max_length=50,
                    ),
                ),
                ("time_of_day", models.TimeField()),
                ("monday", models.BooleanField(default=False)),
                ("tuesday", models.BooleanField(default=False)),
                ("wednesday", models.BooleanField(default=False)),
                ("thursday", models.BooleanField(default=False)),
                ("friday", models.BooleanField(default=False)),
                ("saturday", models.BooleanField(default=False)),
                ("sunday", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Task",
                "verbose_name_plural": "Weekly Tasks",
                "ordering": ["time_of_day"],
            },
        ),
    ]
