# Generated by Django 5.2.4 on 2025-11-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Merge",
            fields=[
                (
                    "lp_bug",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("package", models.CharField(max_length=200)),
                (
                    "merge_type",
                    models.CharField(
                        choices=[
                            ("merge", "merge"),
                            ("sync", "sync"),
                            ("backport", "backport"),
                        ],
                        default="merge",
                        max_length=20,
                    ),
                ),
                ("assignee", models.CharField(blank=True, max_length=100)),
                ("milestone", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("projected", "projected"),
                            ("started", "started"),
                            ("done", "done"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
