# Generated by Django on your request
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LPUser",
            fields=[
                ("username", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("email_md5", models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
