# Generated by Django 5.2

from django.db import migrations, models


def move_review_markers(apps, schema_editor):
    """Mark existing users as team members and import review marker users."""
    LPUser = apps.get_model("launchpad", "LPUser")
    LPReviewMarkerUser = apps.get_model("data_manager", "LPReviewMarkerUser")

    # All existing launchpad users are team members.
    LPUser.objects.update(is_team_member=True)

    # Import every review marker user, creating the LPUser if needed.
    for marker in LPReviewMarkerUser.objects.all():
        user, _ = LPUser.objects.get_or_create(username=marker.username)
        if not user.is_review_marker:
            user.is_review_marker = True
            user.save(update_fields=["is_review_marker"])


def reverse_move_review_markers(apps, schema_editor):
    """Recreate review marker entries from flagged launchpad users."""
    LPUser = apps.get_model("launchpad", "LPUser")
    LPReviewMarkerUser = apps.get_model("data_manager", "LPReviewMarkerUser")

    for user in LPUser.objects.filter(is_review_marker=True):
        LPReviewMarkerUser.objects.get_or_create(username=user.username)


class Migration(migrations.Migration):
    dependencies = [
        ("launchpad", "0004_ubunturelease_status"),
        ("data_manager", "0008_alter_mergebugfiltersettings_subscribers_combined"),
    ]

    operations = [
        migrations.AddField(
            model_name="lpuser",
            name="is_team_member",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lpuser",
            name="is_review_marker",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(move_review_markers, reverse_move_review_markers),
    ]
