# Generated by Django 5.2 on 2026-06-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageMetadata",
            fields=[
                (
                    "slug",
                    models.SlugField(max_length=100, primary_key=True, serialize=False),
                ),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "page metadata",
            },
        ),
    ]
