# Generated by Django 5.2.4 on 2025-11-24 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("launchpad", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lpuser",
            options={
                "verbose_name": "Launchpad user",
                "verbose_name_plural": "Launchpad users",
            },
        ),
    ]
