# Generated by Django 5.2.4 on 2026-04-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("launchpad", "0002_alter_lpuser_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="UbuntuRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adjective", models.CharField(max_length=30, unique=True)),
                ("animal", models.CharField(max_length=30, unique=True)),
                ("version", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "verbose_name": "Ubuntu release",
                "verbose_name_plural": "Ubuntu releases",
            },
        ),
    ]
