# Generated by Django 5.2.4 on 2026-04-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("launchpad", "0003_ubunturelease"),
    ]

    operations = [
        migrations.AddField(
            model_name="ubunturelease",
            name="status",
            field=models.CharField(
                choices=[
                    ("devel", "devel"),
                    ("supported", "supported"),
                    ("esm", "esm"),
                    ("eol", "eol"),
                ],
                default="devel",
                max_length=20,
            ),
        ),
    ]
