# Generated by Django 5.2.7 on 2026-05-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("launchpad", "0004_ubunturelease_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("package", models.CharField(max_length=200)),
                ("release_version", models.CharField(blank=True, max_length=50)),
                ("mp_url", models.URLField(max_length=500)),
                ("reviewer", models.CharField(blank=True, max_length=100)),
                ("submitter", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Needs Review", "Needs Review"),
                            ("Work in Progress", "Work in Progress"),
                            ("Under Review", "Under Review"),
                            ("Approved", "Approved"),
                            ("Needs Fixing", "Needs Fixing"),
                            ("Needs Information", "Needs Information"),
                        ],
                        default="Needs Review",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name="assigned_reviews",
                        to="launchpad.lpuser",
                    ),
                ),
                (
                    "submitter_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name="submitted_reviews",
                        to="launchpad.lpuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
