# Generated by Django 5.2 on 2026-05-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="lines_added",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="lines_removed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="source_branch",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
