# Generated by Django 5.2 on 2026-06-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_lines_added_review_lines_removed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("Needs Review", "Needs Review"),
                    ("Work in Progress", "Work in Progress"),
                    ("Team Approved", "Team Approved"),
                    ("Community Approved", "Community Approved"),
                    ("Approved", "Approved"),
                    ("Needs Fixing", "Needs Fixing"),
                    ("Needs Information", "Needs Information"),
                ],
                default="Needs Review",
                max_length=20,
            ),
        ),
    ]
