# Generated by Django 5.2 on 2026-08-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merges_schedule", "0003_populate_assignee_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merge",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("projected", "projected"),
                    ("started", "started"),
                    ("uploaded", "uploaded"),
                    ("done", "done"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
